"""add tg login

Revision ID: e69d856fcf34
Revises: 5b6e4ba2b1c1
Create Date: 2019-11-06 16:52:32.115244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69d856fcf34'
down_revision = '5b6e4ba2b1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_login', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_tg_login'), 'user', ['tg_login'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_login'), table_name='user')
    op.drop_column('user', 'tg_login')
    # ### end Alembic commands ###
